### ISSUE TITLE
实现格子背景

### ISSUE THREAD

**Issue by nmsn** [mortal-cultivation-biography/daydayup#103]
```css
.background {
    background-size: 14px 14px;
    background-image: linear-gradient(to right, #F6F6F6 1px, transparent 1px), linear-gradient(to bottom, #F6F6F6 1px, transparent 1px);
}
```
